# Generated by Django 5.2 on 2025-04-02 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('FIC', 'Fiction'), ('NON', 'Non-Fiction'), ('SCI', 'Science Fiction'), ('FAN', 'Fantasy'), ('BIO', 'Biography'), ('HOR', 'Horror'), ('ROM', 'Romance'), ('THR', 'Thriller'), ('MYS', 'Mystery')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('membership_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='booklend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lend_date', models.DateField(auto_now_add=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('is_returned', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libmanagement.book')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libmanagement.student')),
            ],
        ),
    ]
