# Generated by Django 5.2 on 2025-04-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('FIC', 'Fiction'), ('NON', 'Non-Fiction'), ('SCI', 'Science Fiction'), ('FAN', 'Fantasy'), ('BIO', 'Biography'), ('HOR', 'Horror'), ('ROM', 'Romance'), ('THR', 'Thriller'), ('MYS', 'Mystery')], default='FIC', max_length=3),
        ),
    ]
