# Generated by Django 5.2 on 2025-04-02 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libmanagement', '0003_rename_booklend_records'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Members',
        ),
    ]
